general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "10px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "52px"
    right: "3px"
    bottom: "3px"
    left: "3px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: true

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "100%"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: "#000000"
      # color: "#a1a1a1"
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: true
      opacity: "100%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: 0
    display_name: "0: Private"
    bind_to_monitor: 1
  - name: 1
    display_name: "1: Term"
    bind_to_monitor: 0
  - name: 2
    display_name: "2: Dev Browser"
    bind_to_monitor: 0
  - name: 3
    display_name: "3: Jira Browsers"
    bind_to_monitor: 0
  - name: 4
    display_name: "4: WebStorm"
    bind_to_monitor: 0
  - name: 5
    bind_to_monitor: 1
  - name: 6
    bind_to_monitor: 1
  - name: 7
    display_name: "7: Comms"
    bind_to_monitor: 1
  - name: 8
    display_name: "8: Comms"
    bind_to_monitor: 1
  - name: 9
    display_name: "9: Ma"
    bind_to_monitor: 1

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
  - commands: ["set-floating"]
    match:
      - window_process: { equals: "SystemSettings" }

  - match:
      - window_process: { equals: "ms-teams.exe" }
    commands: 
      - move --workspace 7

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    display_name: "MODE Resize!!!; Arrows, Shift+Arrows, Esc, Enter"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["Left"]
      - commands: ["resize --width +2%"]
        bindings: ["Right"]
      - commands: ["resize --height +2%"]
        bindings: ["Up"]
      - commands: ["resize --height -2%"]
        bindings: ["Down"]

      - commands: ["resize --width -10%"]
        bindings: ["Shift+Left"]
      - commands: ["resize --width +10%"]
        bindings: ["Shift+Right"]
      - commands: ["resize --height +10%"]
        bindings: ["Shift+Up"]
      - commands: ["resize --height -10%"]
        bindings: ["Shift+Down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["LWin+r"]

  # Disables window management and all other keybindings until Alt+Shift+p
  # is pressed again.
  # - commands: ["wm-toggle-pause"]
  #   bindings: ["Alt+Shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["LWin+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["LWin+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["LWin+Shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["LWin+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["LWin+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["LWin+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["LWin+Ctrl+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["LWin+Ctrl+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["LWin+Ctrl+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["LWin+Ctrl+w"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ["shell-exec cmd"]
  #   bindings: ["Alt+enter"]

  # # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ["focus --next-active-workspace"]
    bindings: ["Alt+PageDown"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["Alt+PageUp"]

  # Focus the workspace that last had focus.
  # - commands: ["focus --recent-workspace"]
  #   bindings: ["Alt+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 0"]
    bindings: ["NumPad0"]
  - commands: ["focus --workspace 1"]
    bindings: ["NumPad1"]
  - commands: ["focus --workspace 2"]
    bindings: ["NumPad2"]
  - commands: ["focus --workspace 3"]
    bindings: ["NumPad3"]
  - commands: ["focus --workspace 4"]
    bindings: ["NumPad4"]
  - commands: ["focus --workspace 5"]
    bindings: ["NumPad5"]
  - commands: ["focus --workspace 6"]
    bindings: ["NumPad6"]
  - commands: ["focus --workspace 7"]
    bindings: ["NumPad7"]
  - commands: ["focus --workspace 8"]
    bindings: ["NumPad8"]
  - commands: ["focus --workspace 9"]
    bindings: ["NumPad9"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 0"]
    bindings: ["Alt+NumPad0"]
  - commands: ["move --workspace 1"]
    bindings: ["Alt+NumPad1"]
  - commands: ["move --workspace 2"]
    bindings: ["Alt+NumPad2"]
  - commands: ["move --workspace 3"]
    bindings: ["Alt+NumPad3"]
  - commands: ["move --workspace 4"]
    bindings: ["Alt+NumPad4"]
  - commands: ["move --workspace 5"]
    bindings: ["Alt+NumPad5"]
  - commands: ["move --workspace 6"]
    bindings: ["Alt+NumPad6"]
  - commands: ["move --workspace 7"]
    bindings: ["Alt+NumPad7"]
  - commands: ["move --workspace 8"]
    bindings: ["Alt+NumPad8"]
  - commands: ["move --workspace 9"]
    bindings: ["Alt+NumPad9"]

  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["LWin+Left"]
  - commands: ["focus --direction right"]
    bindings: ["LWin+Right"]
  - commands: ["focus --direction up"]
    bindings: ["LWin+Up"]
  - commands: ["focus --direction down"]
    bindings: ["LWin+Down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["LWin+Alt+Left"]
  - commands: ["move --direction right"]
    bindings: ["LWin+Alt+Right"]
  - commands: ["move --direction up"]
    bindings: ["LWin+Alt+Up"]
  - commands: ["move --direction down"]
    bindings: ["LWin+Alt+Down"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["LWin+Alt+Ctrl+Left"]
  - commands: ["move-workspace --direction right"]
    bindings: ["LWin+Alt+Ctrl+Right"]
  - commands: ["move-workspace --direction up"]
    bindings: ["LWin+Alt+Ctrl+Up"]
  - commands: ["move-workspace --direction down"]
    bindings: ["LWin+Alt+Ctrl+Down"]
